version: '3'
services:
  web:
    environment: #for Windows10
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true #for Windows10
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests: #for second container
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]